@startuml Clientes

class Cliente {
    - nombre: String
    - email: String
    + realizarPedido(): void
}

class Pedido {
    - id: int
    - fecha: Date
    + agregarProducto(): void
}

class Producto {
    - nombre: String
    - precio: float
}

class Pago {
    - id: int
    - cantidad: float
    - metodo: String
    + procesarPago(): void
}

Cliente "1" -- "0..*" Pedido : realiza >
Pedido "*" -- "1" Producto : contiene >
Cliente "1" -- "0..*" Pago : realiza >

@enduml
